# Generated by Django 3.2 on 2023-04-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='testid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
