# Generated by Django 3.2 on 2023-04-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_testcases_testid'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='testnum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
