# Generated by Django 3.2 on 2023-04-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_problem_testnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='Author',
            field=models.CharField(default='abc', max_length=30),
            preserve_default=False,
        ),
    ]
