# Generated by Django 3.2 on 2023-03-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailid',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
