# Generated by Django 3.2 on 2023-04-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0003_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('C++', 'C++'), ('C', 'C'), ('Python', 'Python'), ('Java', 'Java')], default='C++', max_length=10),
        ),
    ]
