# Generated by Django 3.2 on 2023-04-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0004_alter_submission_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='we', max_length=30),
            preserve_default=False,
        ),
    ]
